version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tylerconlee/slab
    docker:
      - image: circleci/golang:1.10.3
      
    steps:
      - checkout
      - restore_cache:
          keys:
              - glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run:
          name: Install dependencies if not cached
          command: |
              if [ -d ./vendor ]; then
                  echo "vendor directory found"
              else
                  echo "vendor directory not found"
                  curl https://glide.sh/get | sh
                  glide install
              fi
      - save_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
              - vendor
  test:
    working_directory: /go/src/github.com/tylerconlee/slab
    docker:
      - image: circleci/golang:1.10.3
      - image: circleci/redis:4
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run: go get -u github.com/jstemmer/go-junit-report 
      - run: mkdir go-test 
      - run: go test -v $(go list ./... | grep -v /vendor/) | go-junit-report > go-test/results.xml
      - store_test_results:
           path: go-test/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build