version: 2
jobs:
  build:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/slab
      
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - save_cache:
          key: src-{{ .Branch }}-{{ checksum "main.go" }}
          paths:
            - "src/"
  test:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/slab
    steps:
      - checkout
      - restore_cache:
          key: src-{{ .Branch }}-{{ checksum "main.go" }}
      - run: go test -v
  deploy:
    working_directory: ~/slab
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/slab
    steps:
      - checkout
      - restore_cache:
          key: src-{{ .Branch }}-{{ checksum "main.go" }}
      - run: make
      - run: make deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      