version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tylerconlee/slab
    docker:
      - image: circleci/golang:1.8.1
      
    steps:
      - checkout
      - restore_cache:
          keys:
              - glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run:
          name: Install dependencies if not cached
          command: |
              if [ -d ./vendor ]; then
                  echo "vendor directory found"
              else
                  echo "vendor directory not found"
                  curl https://glide.sh/get | sh
                  glide install
              fi
      - save_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
              - vendor
  test:
    working_directory: /go/src/github.com/tylerconlee/slab
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - restore_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run: go test -v $(go list ./... | grep -v /vendor/) 
  deploy:
    working_directory: /go/src/github.com/tylerconlee/slab
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - restore_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run: make
      - run: make deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      